sudo: required
dist: trusty

language: crystal

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: V8_VERSION=6.3.292.48.1
    - os: osx
      osx_image: xcode9.2
      env: V8_VERSION=6.3.292.48.1

install: ./travis/install.sh